#!/usr/bin/env ruby
$: << File.join(File.dirname(__FILE__), '..', 'lib')

require 'socket'

server = TCPServer.new('localhost', 2345)

loop do
    # Wait for client to connect before returning a TCPSocket
    socket = server.accept

    # Read first line of request
    request = socket.gets

    STDERR.puts request

    response = "Hello world!\n"

    # Response headers
    socket.print "HTTP/1.1 200 OK\r\n" +
                 "Content-Type: text/plain\r\n" +
                 "Content-Length: #{response.bytesize}\r\n" +
                 "Connection: close\r\n"

    # Blank line separating headers from body is required
    socket.print "\r\n"

    # Response body
    socket.print response

    # Close the socket
    socket.close
end